# Generated by Django 2.2.3 on 2019-07-26 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDeleteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ManyToManyParent',
            fields=[
                ('reportdeletemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delete_example.ReportDeleteModel')),
            ],
            bases=('delete_example.reportdeletemodel',),
        ),
        migrations.CreateModel(
            name='ManyToOneParent',
            fields=[
                ('reportdeletemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delete_example.ReportDeleteModel')),
            ],
            bases=('delete_example.reportdeletemodel',),
        ),
        migrations.CreateModel(
            name='OneToOneParent',
            fields=[
                ('reportdeletemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delete_example.ReportDeleteModel')),
            ],
            bases=('delete_example.reportdeletemodel',),
        ),
        migrations.CreateModel(
            name='OneToOneChildProtect',
            fields=[
                ('reportdeletemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delete_example.ReportDeleteModel')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='child_protect', to='delete_example.OneToOneParent')),
            ],
            bases=('delete_example.reportdeletemodel',),
        ),
        migrations.CreateModel(
            name='OneToOneChildNull',
            fields=[
                ('reportdeletemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delete_example.ReportDeleteModel')),
                ('parent', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_null', to='delete_example.OneToOneParent')),
            ],
            bases=('delete_example.reportdeletemodel',),
        ),
        migrations.CreateModel(
            name='OneToOneChildCascade',
            fields=[
                ('reportdeletemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delete_example.ReportDeleteModel')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child_cascade', to='delete_example.OneToOneParent')),
            ],
            bases=('delete_example.reportdeletemodel',),
        ),
        migrations.CreateModel(
            name='ManyToOneChildProtect',
            fields=[
                ('reportdeletemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delete_example.ReportDeleteModel')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children_protect', to='delete_example.ManyToOneParent')),
            ],
            bases=('delete_example.reportdeletemodel',),
        ),
        migrations.CreateModel(
            name='ManyToOneChildNull',
            fields=[
                ('reportdeletemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delete_example.ReportDeleteModel')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_null', to='delete_example.ManyToOneParent')),
            ],
            bases=('delete_example.reportdeletemodel',),
        ),
        migrations.CreateModel(
            name='ManyToOneChildCascade',
            fields=[
                ('reportdeletemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delete_example.ReportDeleteModel')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_cascade', to='delete_example.ManyToOneParent')),
            ],
            bases=('delete_example.reportdeletemodel',),
        ),
        migrations.CreateModel(
            name='ManyToManyChild',
            fields=[
                ('reportdeletemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delete_example.ReportDeleteModel')),
                ('parents', models.ManyToManyField(related_name='children', to='delete_example.ManyToManyParent')),
            ],
            bases=('delete_example.reportdeletemodel',),
        ),
    ]
