# Generated by Django 2.2.3 on 2019-07-20 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneOfManyItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='OneToOneItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SharedItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('many_items_cascade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_cascade', to='delete_example.OneOfManyItems')),
                ('many_items_null', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_null', to='delete_example.OneOfManyItems')),
                ('many_items_protect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_protect', to='delete_example.OneOfManyItems')),
                ('one_item_cascade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_cascade', to='delete_example.OneToOneItem')),
                ('one_item_null', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_null', to='delete_example.OneToOneItem')),
                ('one_item_protect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_protect', to='delete_example.OneToOneItem')),
                ('shared_item_cascade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_cascade', to='delete_example.SharedItem')),
                ('shared_item_null', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_null', to='delete_example.SharedItem')),
                ('shared_item_protect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_protect', to='delete_example.SharedItem')),
            ],
        ),
    ]
